# Generated by Django 5.1.2 on 2024-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_accountnumber_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='cf5330', max_length=6, unique=True, verbose_name='Account Number'),
        ),
    ]
