# Generated by Django 5.1.2 on 2024-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_otp_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encrypted_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='ef77b5', max_length=6, unique=True, verbose_name='Account Number'),
        ),
    ]
