# Generated by Django 5.1.2 on 2024-10-27 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_encrypted_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='1bb901', max_length=6, unique=True, verbose_name='Account Number'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('CASH_DEPOSIT', 'Cash Deposit'), ('CASH_TRANSFER', 'Cash Transfer'), ('SUBSCRIPTION', 'Subscription'), ('ASSET_PURCHASE', 'Asset Purchase'), ('ASSET_SELL', 'Asset Sell')], max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='users.bankaccount')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='users.bankaccount')),
            ],
        ),
    ]
