# Generated by Django 5.1.2 on 2024-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_accountnumber_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='ee2cb4', max_length=6, unique=True, verbose_name='Account Number'),
        ),
    ]
