# Generated by Django 5.1.2 on 2024-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(default='4709cc', max_length=6, unique=True, verbose_name='Account Number'),
        ),
    ]
