# Generated by Django 5.1.2 on 2024-10-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_accountnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='transactionDate',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='transactionType',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sourceAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingTransactions', to='users.bankaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='targetAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomingTransactions', to='users.bankaccount'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountNumber',
            field=models.CharField(max_length=6, unique=True, verbose_name='Account Number'),
        ),
    ]
