# Generated by Django 5.1.2 on 2024-10-27 21:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_transaction_date_transaction_transactiondate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset_symbol')},
            },
        ),
    ]
