# Generated by Django 5.1.2 on 2024-10-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userasset',
            old_name='asset_symbol',
            new_name='assetSymbol',
        ),
        migrations.AlterUniqueTogether(
            name='userasset',
            unique_together={('user', 'assetSymbol')},
        ),
    ]
