# Generated by Django 5.1.2 on 2024-10-28 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_autoinvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinvest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
